name: 'My First GitHub Actions'
on:
  push:
    branches:
    - master
    tags:
    - 'v*'
  pull_request:
    branches:
    - master

jobs:
  call_build:
    uses: ./.github/workflows/ci.yaml
    with:
      artifact_name: apiapp
      automatic_release_tag: "latest"

  call_release:
    uses: ./.github/workflows/cd.yaml
    needs: call_build
    with:
      title: latest
      automatic_release_tag: "latest"
      artifact_name: apiapp
    secrets: inherit
