name: 'My First GitHub Actions'
on: push

jobs:
  first-job:
    name: 'First Job'
    runs-on: ubuntu-latest

    steps:
    - name: Show secret
      shell: bash
      run: |
        echo ${{ secrets.SECRET }}

    - name: Check secret
      shell: pwsh
      run: |
        if ("${{ secrets.SECRET }}" -eq "World") {
            echo "YES!"
        } else {
            echo "NO!"
        }
